import { Link } from "wouter";
import { ShieldCheck, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-background/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-3 flex items-center gap-3">
          <Link href="/">
            <Button variant="ghost" size="icon" data-testid="button-back-home">
              <ArrowLeft className="w-4 h-4" />
            </Button>
          </Link>
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-md bg-primary flex items-center justify-center">
              <ShieldCheck className="w-5 h-5 text-primary-foreground" />
            </div>
            <h1 className="text-lg font-semibold tracking-tight" data-testid="text-terms-title">Terms of Service</h1>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-8">
        <Card className="p-6 sm:p-8 space-y-8">
          <div className="space-y-2">
            <p className="text-sm text-muted-foreground" data-testid="text-terms-effective-date">
              Effective Date: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              These Terms of Service ("Terms") govern your access to and use of SignSafe ("the Service"). By using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
            </p>
          </div>

          <section className="space-y-3" data-testid="section-ai-disclaimer">
            <h2 className="text-base font-semibold">1. AI Disclaimer — Not Legal Advice</h2>
            <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
              <p className="font-medium text-foreground">SignSafe is an AI-powered informational tool only. It does not provide legal advice.</p>
              <p>The analysis, translations, risk assessments, and other outputs generated by SignSafe are produced by artificial intelligence (DigitalOcean Gradient AI / Meta Llama 3.3 70B) and are intended for informational and educational purposes only. They should not be considered a substitute for professional legal advice.</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>AI-generated analysis may contain errors, omissions, or misinterpretations.</li>
                <li>Do not rely solely on SignSafe's output to make legal decisions.</li>
                <li>Always consult a qualified attorney for legal matters.</li>
                <li>SignSafe is not a law firm and does not create an attorney-client relationship.</li>
              </ul>
            </div>
          </section>

          <section className="space-y-3" data-testid="section-service-description">
            <h2 className="text-base font-semibold">2. Service Description</h2>
            <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
              <p>SignSafe provides AI-powered legal document analysis, including:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Plain English translation of legal documents.</li>
                <li>Risk identification and severity assessment.</li>
                <li>Key legal term definitions.</li>
                <li>AI-powered Q&A about document contents.</li>
                <li>Document scanning via image/photo upload (OCR).</li>
              </ul>
            </div>
          </section>

          <section className="space-y-3" data-testid="section-accounts">
            <h2 className="text-base font-semibold">3. User Accounts</h2>
            <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
              <p>To use SignSafe, you must create an account. You are responsible for:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Providing accurate and complete registration information.</li>
                <li>Maintaining the security of your account credentials.</li>
                <li>All activities that occur under your account.</li>
              </ul>
              <p>You must be at least 13 years old to create an account and use the Service.</p>
            </div>
          </section>

          <section className="space-y-3" data-testid="section-subscription">
            <h2 className="text-base font-semibold">4. Free Tier & Premium Subscriptions</h2>
            <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
              <p><span className="font-medium text-foreground">Free Tier:</span> All users receive 3 free document analyses per calendar month. The counter resets at the beginning of each month.</p>
              <p><span className="font-medium text-foreground">Premium Subscription:</span> Premium users enjoy unlimited document analyses. Subscription details:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Subscriptions are billed on a recurring basis (monthly or annually, as selected).</li>
                <li>Subscriptions auto-renew unless cancelled before the end of the current billing period.</li>
                <li>You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period.</li>
                <li>Refunds are handled in accordance with the applicable app store's refund policy (Apple App Store, Google Play Store).</li>
              </ul>
            </div>
          </section>

          <section className="space-y-3" data-testid="section-acceptable-use">
            <h2 className="text-base font-semibold">5. Acceptable Use</h2>
            <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
              <p>You agree not to:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
                <li>Submit documents containing malicious content, malware, or code injection attempts.</li>
                <li>Attempt to reverse-engineer, decompile, or extract the AI models or algorithms used by the Service.</li>
                <li>Automate access to the Service (scraping, bots) without written permission.</li>
                <li>Interfere with or disrupt the Service or its infrastructure.</li>
                <li>Share your account credentials with others or allow unauthorized access.</li>
                <li>Use the Service to process documents you do not have the right to access.</li>
              </ul>
            </div>
          </section>

          <section className="space-y-3" data-testid="section-intellectual-property">
            <h2 className="text-base font-semibold">6. Intellectual Property</h2>
            <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
              <p>You retain ownership of documents you submit to SignSafe. By submitting documents, you grant us a limited, non-exclusive license to process your documents through our AI system solely for the purpose of providing the Service to you.</p>
              <p>The SignSafe application, including its design, code, AI prompts, and branding, is the intellectual property of SignSafe and is protected by applicable intellectual property laws.</p>
            </div>
          </section>

          <section className="space-y-3" data-testid="section-limitation-liability">
            <h2 className="text-base font-semibold">7. Limitation of Liability</h2>
            <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
              <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, PLAINLEGAL SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Your use or inability to use the Service.</li>
                <li>Any errors, inaccuracies, or omissions in AI-generated analysis.</li>
                <li>Unauthorized access to or alteration of your data.</li>
                <li>Any legal decisions made based on the Service's output.</li>
              </ul>
            </div>
          </section>

          <section className="space-y-3" data-testid="section-account-deletion">
            <h2 className="text-base font-semibold">8. Account Deletion</h2>
            <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
              <p>You may delete your account at any time through the account settings. Upon account deletion:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>All personal data, documents, analysis results, and chat history will be permanently and irreversibly deleted.</li>
                <li>Any active premium subscription should be cancelled separately through the applicable app store before deleting your account.</li>
                <li>We cannot recover deleted accounts or data.</li>
              </ul>
            </div>
          </section>

          <section className="space-y-3" data-testid="section-termination">
            <h2 className="text-base font-semibold">9. Termination</h2>
            <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
              <p>We reserve the right to suspend or terminate your account at our discretion, with or without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.</p>
            </div>
          </section>

          <section className="space-y-3" data-testid="section-changes">
            <h2 className="text-base font-semibold">10. Changes to These Terms</h2>
            <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
              <p>We may modify these Terms at any time. Changes will be effective when posted. Your continued use of the Service after changes are posted constitutes acceptance of the updated Terms. We encourage you to review these Terms periodically.</p>
            </div>
          </section>

          <section className="space-y-3" data-testid="section-contact">
            <h2 className="text-base font-semibold">11. Contact Us</h2>
            <div className="space-y-2 text-sm text-muted-foreground leading-relaxed">
              <p>If you have questions about these Terms of Service, please contact us at:</p>
              <p className="font-medium text-foreground">support@signsafe.app</p>
            </div>
          </section>
        </Card>
      </main>

      <footer className="border-t mt-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-muted-foreground">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>SignSafe</span>
          </div>
          <div className="flex items-center gap-4">
            <Link href="/privacy">
              <span className="hover:underline cursor-pointer" data-testid="link-privacy-from-terms">Privacy Policy</span>
            </Link>
            <span className="font-medium">Terms of Service</span>
          </div>
        </div>
      </footer>
    </div>
  );
}